# Inference of Vad task

test_data: "sample_data/vad_eval_data.json"
result_path: "test_logs/debug"
task_config: "sample_data/model/demo_task/crdnn.yaml"
chkpt_name: null
chkpt_aver: true

export_quant_model: true
export_onnx_model:
  do_export: true
  chunk_size: 10

post_process: 
  type: "sliding_window" # no_post_process also available
  config:
    window_size: 10
    speech_start_thres: 0.5
    speech_end_thres: 0.9

# --- no_post_process config ---
# post_process: 
#   type: "no_post_process" # no_post_process also available
#   config:
#     dummy_conf: -1

trainer:
  accelerator: "gpu" 
  devices: 1 
  strategy: "ddp" 